In [1]:
import numpy as np

Find neighbours, modified from: [code](https://github.com/MaxRudometkin/2d_array_neighbours/blob/2c88bee8078b388bd12802c4f62bc2062c84abb9/array_neighbours.py#L85) found off [here](https://pyquestions.com/find-neighbors-in-a-matrix)

In [ ]:
import time

def find_all_neighbours(adj_mat):
    """
    This method takes 2d array and return list of all elements
    with all neighbours
    :param arr: 2d array
    :return: list of array elements with all neighbours
    """    
    neighbors = []
    arr = np.asarray(adj_mat) # change matrix to array
    for i in range(len(arr)):
        for j, value in enumerate(arr[i]):
            if i == 0 or i == len(arr) - 1 or j == 0 or j == len(arr[i]) - 1:
                # corners
                new_neighbors = []
                if i != 0 and j != 0:
                    new_neighbors.append(arr[i - 1][j - 1])  # left top neighbour
                if i != 0 :
                    new_neighbors.append(arr[i - 1][j])  # top neighbor
                if i != 0 and j != len(arr[i]) - 1 :
                    new_neighbors.append(arr[i - 1][j + 1])  # right top neighbour
                if j != len(arr[i]) - 1 :
                    new_neighbors.append(arr[i][j + 1])  # right neighbor
                if i != len(arr) - 1 and j != len(arr[i]) - 1 :
                    new_neighbors.append(arr[i + 1][j + 1])  # right bottom neighbour
                if i != len(arr) - 1 :
                    new_neighbors.append(arr[i + 1][j])  # bottom neighbor
                if i != len(arr) - 1 and j != 0:
                    new_neighbors.append(arr[i + 1][j - 1])  # left bottom neighbour
                if j != 0:
                    new_neighbors.append(arr[i][j - 1])  # left neighbor
            else:
                # add neighbors
                new_neighbors = [
                    arr[i - 1][j - 1],  # left top neighbour
                    arr[i - 1][j],  # top neighbor
                    arr[i - 1][j + 1],  # right top neighbour
                    arr[i][j + 1],  # right neighbor
                    arr[i + 1][j + 1],  # right bottom neighbour
                    arr[i + 1][j],  # bottom neighbor
                    arr[i + 1][j - 1],  # left bottom neighbour
                    arr[i][j - 1]  # left neighbor
                ]

            neighbors.append({
                "index": i * len(arr[i]) + j,
                "value": value,
                "neighbors": new_neighbors})

    return neighbors

def get_neighbours(all_neighbours):
    starttime = time.time()
    print('This takes awhile')
    
    neighbours = find_all_neighbours(all_neighbours)
    
    endtime = time.time()
    print('time to get all neighbours: ', endtime - starttime)
    
    return list(filter(lambda x: x['value'] != 0, neighbours)) # only return for when value != 0 (ie. cell is present)

def get_mean_cell_neighborhood(neighbours):
    starttime = time.time()
    
    neighbs = get_neighbours(neighbours)
    
    sum_neighb_cells = []
    for i in neighbs:
        for key in i:
            if key == 'neighbors':
                sum_neighb_cells.append(sum(i[key]))
                
    endtime = time.time()
    print('time to get avg cell neighbourhood: ', endtime - starttime)
    return sum(sum_neighb_cells)/len(sum_neighb_cells)

In [ ]:
arr = [[1, 0, 0, 0],
      [0, 1, 0, 1],
      [0,0,0,0],
      [1,1,0,1]]

In [ ]:
get_neighbours(arr)

In [ ]:
find_all_neighbours(arr)

In [63]:
m = np.matrix([[1., 2., 0., 0.],
      [0., 1., 0., 0.],
      [1.,0.,2.,1.],
      [1.,1.,1.,1.]])
m

matrix([[1., 2., 0., 0.],
        [0., 1., 0., 0.],
        [1., 0., 2., 1.],
        [1., 1., 1., 1.]])

In [64]:
(m[np.where(m != 0)]).size # count how many non-zero values

10

In [65]:
for i in range(len(m)):
    print((m[np.where(m[i] != 0)]).size)

2
1
3
4


In [67]:
for i in range(len(m)):
    print(m[i][np.where(m[i] != 0)])

[[1. 2.]]
[[1.]]
[[1. 2. 1.]]
[[1. 1. 1. 1.]]
